# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('newsletter', '0004_auto_20180407_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='auth.Group', verbose_name='Groups'),
        ),
    ]
