# Generated by Django 2.2.16 on 2020-10-09 18:21

import django.db.models.deletion
from django.db import migrations, models

import newsletter.models


class Migration(migrations.Migration):
    dependencies = [
        ('newsletter', '0005_auto_20190918_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=newsletter.models.attachment_upload_to, verbose_name='attachment')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments',
                                              to='newsletter.Message', verbose_name='message')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
    ]
