# Generated by Django 2.1.7 on 2019-03-17 02:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20190208_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='activation_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='activation code'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='activation_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='activation code legacy'),
        ),
    ]
