# Generated by Django 5.2.2 on 2025-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_longer_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_thumbnail_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='image thumbnail width'),
        ),
    ]
