# Generated by Django 3.1.7 on 2021-03-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_longer_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subscription_generator_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
