# Generated by Django 3.1.5 on 2021-01-10 14:28
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def get_site_id():
    if hasattr(settings, "SITE_ID"):
        return settings.SITE_ID
    else:
        return 1


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('newsletter', '0008_longer_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='site',
            field=models.ForeignKey(default=get_site_id, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site for this submission'),
            preserve_default=False,
        ),
    ]
