# Generated by Django 5.2.6 on 2025-09-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_article_image_thumbnail_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='enable_unsubscribe',
            field=models.BooleanField(default=True, help_text='Enable unsubscribe links in e-mails.', verbose_name='enable unsubscribe'),
        ),
    ]
