# Generated by Django 5.2.5 on 2025-08-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_newsletter_enable_unsubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subscription_generator_class',
            field=models.CharField(blank=True, help_text='Class for generating subscriptions dynamically', max_length=200, null=True, verbose_name='subscription generator class'),
        ),
    ]
