# Generated by Django 5.2.6 on 2025-10-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_submission_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_below_text',
            field=models.BooleanField(default=False),
        ),
    ]
