# Generated by Django 5.2.13 on 2026-04-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_article_image_below_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_use_original',
            field=models.BooleanField(default=False, verbose_name='use original image'),
        ),
    ]
