# Generated by Django 5.2.12 on 2026-03-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0014_article_image_below_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="send_text",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not to send text versions of e-mails.",
                verbose_name="send text",
            ),
        ),
    ]
